name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: install deps
        run: pnpm install

      - name: build site
        run: pnpm build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./dist --project-name honcdev
